app:
  name: short-video-api
  version: v0.0.1
  trace_endpoint: http://localhost:14268/api/traces # jaeger endpoint
#  trace_endpoint: http://localhost:4317

components:
  etcd:
    default:
      host: localhost
      port: 2379
  consul:
    default:
      address: localhost:8500
